#!/usr/bin/env python3
"""Summarise the GEMM calls that reach rocBLAS on gfx1151.

ADR 0012 rule 8: the tables in rocblas-on-gfx1151.md are generated by this
script from gemm_shapes_gfx1151.tsv, never typed by hand.

Why these shapes and not a synthetic set: every GEMM here was captured with
ROCBLAS_LAYER=2 from a real image request. Benchmarking invented shapes
measures a kernel nobody runs.

Attribution rule: a GEMM is attributed to the language model when one of its
matrix dimensions equals that model's embedding or feed-forward width, and to
the vision tower when it matches the tower's. Both come from GGUF metadata
(/api/show), never from eyeballing the shapes -- an early draft of this table
guessed qwen3.8's tower at 1152/4304 by analogy with gemma4, and qwen3.8 does
not report vision dims at all. Anything matching neither is reported as
"other" rather than assigned to whichever bucket looks plausible; the
projector GEMMs legitimately land there.
"""
import collections
import os
import sys

# From GGUF metadata via /api/show: (lm_embd, lm_ffn, vis_embd, vis_ffn).
# 0 means the model does not report that field -- never a dimension to match.
MODEL_DIMS = {
    "gemma4:31b-it-q4_K_M":     (5376, 21504, 1152, 4304),
    "gemma4:26b-a4b-it-q4_K_M": (2816,  2112, 1152, 4304),
    "qwen3.8:27b-q4_K_M":       (5120, 17408,    0,    0),
    "nemotron3:33b-q4_K_M":     (1024,  4096, 1280, 5120),
    "qwen3.6:35b-a3b-q4_k_m":   (2048,     0, 1152,    0),
}


def load(path):
    rows = []
    with open(path) as fh:
        for ln in fh:
            if ln.startswith("#") or not ln.strip():
                continue
            model, dtype, trans, m, n, k = ln.rstrip("\n").split("\t")
            rows.append((model, dtype, trans, int(m), int(n), int(k)))
    return rows


def classify(model, m, k):
    dims = MODEL_DIMS.get(model)
    if not dims:
        return "other"
    lm = {d for d in dims[:2] if d}
    vis = {d for d in dims[2:] if d}
    if lm & {m, k}:
        return "LM"
    if vis & {m, k}:
        return "tower"
    return "other"


def gflop(m, n, k):
    return 2 * m * n * k / 1e9


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    rows = load(sys.argv[1] if len(sys.argv) > 1
                else os.path.join(here, "gemm_shapes_gfx1151.tsv"))

    per = collections.defaultdict(collections.Counter)
    calls = collections.Counter()
    dtypes = collections.defaultdict(collections.Counter)
    for model, dt, _tr, m, n, k in rows:
        per[model][classify(model, m, k)] += gflop(m, n, k)
        calls[model] += 1
        dtypes[model][dt] += 1

    print("### rocBLAS work per image request\n")
    print("| model | calls | total TFLOP | tower | LM | other | dtypes |")
    print("|---|---|---|---|---|---|---|")
    for model in sorted(per, key=lambda x: -sum(per[x].values())):
        c, tot = per[model], sum(per[model].values())
        cell = lambda v: f"{v/1e3:.2f}" if v else "—"
        dts = ", ".join(f"{n}x {d}" for d, n in dtypes[model].most_common())
        print(f"| `{model}` | {calls[model]} | **{tot/1e3:.2f}** | "
              f"{cell(c['tower'])} | {cell(c['LM'])} | {cell(c['other'])} | {dts} |")

    print("\n### Distinct shapes, by total cost\n")
    print("| model | calls | dtype | m | n | k | GFLOP each | attributed |")
    print("|---|---|---|---|---|---|---|---|")
    shapes = collections.Counter()
    for model, dt, _tr, m, n, k in rows:
        shapes[(model, dt, m, n, k)] += 1
    ranked = sorted(shapes.items(), key=lambda kv: -gflop(*kv[0][2:]) * kv[1])
    for (model, dt, m, n, k), cnt in ranked[:12]:
        print(f"| `{model}` | {cnt} | {dt} | {m} | {n} | {k} | "
              f"{gflop(m, n, k):.2f} | {classify(model, m, k)} |")


if __name__ == "__main__":
    main()
