#!/usr/bin/env python3
"""mmq-native-shim.py <llama.cpp checkout> <shim root>

Build the CPU padding sweep (docs/maxusai/tasks/mmq-rules-check.cu) without a CUDA toolkit, e.g. on macOS.

The sweep only evaluates MMQ's config tables and size helpers on the host; it needed nvcc because it #includes
ggml-cuda/mmq.cuh, whose other half is device code. This writes a replacement mmq.cuh (and mmvq.cuh) under
<shim root>/ggml/src/ggml-cuda/ that contains ONLY the host-evaluable definitions the sweep uses, each copied
VERBATIM from the checkout given -- nothing is re-typed -- so the same, unmodified sweep source compiles with any
C++17 compiler:

    clang++ -std=c++17 -x c++ -I<shim root> -I<checkout> -I<checkout>/ggml/include -I<checkout>/ggml/src \
        -I<checkout>/ggml/src/ggml-cuda mmq-rules-check.cu -o mmq-rules-check-native

Under nvcc the arch-dependent choices go through ggml_cuda_highest_compiled_arch(), which build-check.sh's gencode
list makes the identity for every NVIDIA arch the sweep models (sm_70/75/80/86/89/90/120). Without
__CUDA_ARCH_LIST__, common.cuh's own fallback is exactly that identity, and this shim uses it -- after checking the
checkout still has that fallback. An AMD cc never reaches it.

Every item is required: if the checkout renames or moves one, this exits non-zero naming it, rather than build a
sweep that models something else. Validated by reproducing an nvcc build's output byte for byte (see the README).
"""
import os
import re
import sys

SRC, OUT = sys.argv[1], sys.argv[2]
CUDA = os.path.join(SRC, "ggml", "src", "ggml-cuda")


def read(name):
    with open(os.path.join(CUDA, name)) as fh:
        return fh.read()


def fail(msg):
    sys.exit(f"mmq-native-shim: {msg} ({SRC})")


def block_from(text, start, name):
    """Text from `start` through the brace that closes the first '{' after it (plus a trailing ';' if present)."""
    i = text.find("{", start)
    if i < 0:
        fail(f"no body for {name}")
    depth = 0
    for j in range(i, len(text)):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = j + 1
                if text[end:end + 1] == ";":
                    end += 1
                return text[start:end]
    fail(f"unbalanced braces in {name}")


def func(text, name, must=None):
    """A function definition by name; `must` is a regex the signature line must also match (to pick an overload)."""
    for m in re.finditer(r"^[^\n;{}]*\b" + re.escape(name) + r"\s*\([^\n]*$", text, re.M):
        line = m.group(0)
        if "#define" in line or line.strip().startswith("//") or line.rstrip().endswith(";"):
            continue
        if must and not re.search(must, line):
            continue
        return block_from(text, m.start(), name)
    fail(f"function {name} not found" + (f" (signature matching {must!r})" if must else ""))


def struct(text, name):
    m = re.search(r"^(struct|enum)\s+" + re.escape(name) + r"\s*\{", text, re.M)
    if not m:
        fail(f"type {name} not found")
    return block_from(text, m.start(), name)


def macro_lines(text, prefix):
    """Every #define whose name starts with prefix, with its backslash continuations."""
    out, lines, i = [], text.split("\n"), 0
    while i < len(lines):
        if re.match(r"#\s*define\s+" + re.escape(prefix), lines[i]):
            out.append(lines[i])
            while lines[i].rstrip().endswith("\\"):
                i += 1
                out.append(lines[i])
        i += 1
    if not out:
        fail(f"no #define {prefix}*")
    return "\n".join(out)


def line_matching(text, pattern, what):
    m = re.search(pattern, text, re.M)
    if not m:
        fail(f"{what} not found")
    return m.group(0)


common, mmq, mmvq = read("common.cuh"), read("mmq.cuh"), read("mmvq.cuh")
with open(os.path.join(SRC, "ggml", "src", "ggml-common.h")) as fh:
    ggml_common = fh.read()
# ggml-common.h defines QI*/QR* only for the GPU backends (GGML_COMMON_DECL_CUDA/HIP/SYCL); the C++ declaration
# this shim includes has the QK* sizes but not these, so they are copied from that block verbatim.
gpu_block = ggml_common[ggml_common.index("#if defined(GGML_COMMON_DECL_CUDA) || defined(GGML_COMMON_DECL_HIP)"):]
gpu_block = gpu_block[:gpu_block.index("#endif // GGML_COMMON_DECL_CUDA || GGML_COMMON_DECL_HIP")]

# common.cuh's own fallback when __CUDA_ARCH_LIST__ is undefined: the identity. Refuse if it has changed.
if not re.search(r"#else\s*\n\s*static int ggml_cuda_highest_compiled_arch\(const int arch\) \{\s*return arch;\s*\}",
                 common):
    fail("common.cuh's non-__CUDA_ARCH_LIST__ fallback for ggml_cuda_highest_compiled_arch is not the identity")

parts = [
    "// GENERATED by docs/maxusai/tasks/mmq-native-shim.py from " + os.path.abspath(SRC) + " -- do not edit.",
    "// Host-only subset of ggml-cuda/mmq.cuh (and common.cuh) for the CPU padding sweep; every definition below",
    "// is copied verbatim from that checkout. See the generator's docstring.",
    "#pragma once",
    "#include <climits>",
    "#include <cstddef>",
    "#include <cstdint>",
    "#include <cstdio>",
    "#include <algorithm>",
    '#include "ggml.h"',
    "#define GGML_COMMON_DECL_CPP",
    '#include "ggml-common.h"',
    "#define __host__",
    "#define __device__",
    "#define __forceinline__ inline",
    "#define __restrict__",
    "",
    "// ggml-common.h, its GPU-backend QI/QR block",
    macro_lines(gpu_block, "QI"),
    macro_lines(gpu_block, "QR"),
    "",
    "// common.cuh",
    macro_lines(common, "GGML_CUDA_CC_"),
    "static int ggml_cuda_highest_compiled_arch(const int arch) {\n    return arch;\n}  // common.cuh's fallback, checked",
]
for f in ["amd_mfma_available", "amd_wmma_available", "volta_mma_available", "turing_mma_available",
          "ampere_mma_available", "blackwell_mma_available"]:
    parts.append(func(common, f))

parts += [
    "",
    "// mmq.cuh",
    macro_lines(mmq, "MMQ_"),
    line_matching(mmq, r"^static constexpr int QK8_1_MMQ\s*=.*$", "QK8_1_MMQ"),
    line_matching(mmq, r"^static constexpr int QK_FP4_MMQ\s*=.*$", "QK_FP4_MMQ"),
    # Only its size is used. mmq.cuh asserts sizeof(block_q8_1_mmq) == QK8_1_MMQ + 4*sizeof(half2), and half2 is
    # 4 bytes; that assertion is required to be present below, so a layout change fails here, not silently.
    "struct block_q8_1_mmq { char opaque[QK8_1_MMQ + 4*4]; };",
    line_matching(mmq, r"^static_assert\(sizeof\(block_q8_1_mmq\) == QK8_1_MMQ \+ 4\*sizeof\(half2\).*$",
                  "the block_q8_1_mmq size assertion"),
    struct(mmq, "ggml_cuda_mmq_sram_layout"),
    func(mmq, "ggml_cuda_mmq_get_sram_stride"),
    struct(mmq, "tile_x_sizes"),
    func(mmq, "mmq_get_dp4a_tile_x_sizes"),
    struct(mmq, "ggml_cuda_mmq_config"),
    macro_lines(mmq, "CASE"),
]
incs = re.findall(r'^#include "mmq-config-[a-z0-9-]+\.cuh"$', mmq, re.M)
if len(incs) < 10:
    fail(f"expected the ten mmq-config-*.cuh includes, found {len(incs)}")
parts += incs
parts.append(func(mmq, "ggml_cuda_mmq_get_config", must=r"__host__.*const int cc"))
parts.append(func(mmq, "ggml_cuda_mmq_get_nbytes_shared_x"))
if re.search(r"\bggml_cuda_mmq_get_nbytes_y_tile\s*\(", mmq):
    parts.append(func(mmq, "ggml_cuda_mmq_get_nbytes_y_tile"))
parts.append(func(mmq, "mmq_get_nbytes_shared"))
parts.append("#undef half2")

shim_dir = os.path.join(OUT, "ggml", "src", "ggml-cuda")
os.makedirs(shim_dir, exist_ok=True)
with open(os.path.join(shim_dir, "mmq.cuh"), "w") as fh:
    fh.write("\n\n".join(parts).replace("sizeof(half2)", "4") + "\n")
with open(os.path.join(shim_dir, "mmvq.cuh"), "w") as fh:
    fh.write("#pragma once\n" + macro_lines(mmvq, "MMVQ_MAX_BATCH_SIZE") + "\n")
print(f"mmq-native-shim: wrote {shim_dir}/mmq.cuh and mmvq.cuh from {SRC}")
